/* soapH.h
   Generated by gSOAP 2.8.21 from soap-repo.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data),0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data),0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);

#ifndef soap_write_unsignedByte
#define soap_write_unsignedByte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_unsignedByte(soap, data),0) || soap_put_unsignedByte(soap, data, "unsignedByte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);

#ifndef soap_read_unsignedByte
#define soap_read_unsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data),0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data),0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data),0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data),0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data),0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns__remove
#define SOAP_TYPE_ns__remove (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__remove(struct soap*, struct ns__remove *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__remove(struct soap*, const struct ns__remove *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__remove(struct soap*, const char*, int, const struct ns__remove *, const char*);
SOAP_FMAC3 struct ns__remove * SOAP_FMAC4 soap_in_ns__remove(struct soap*, const char*, struct ns__remove *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__remove(struct soap*, const struct ns__remove *, const char*, const char*);

#ifndef soap_write_ns__remove
#define soap_write_ns__remove(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__remove(soap, data),0) || soap_put_ns__remove(soap, data, "ns:remove", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__remove * SOAP_FMAC4 soap_get_ns__remove(struct soap*, struct ns__remove *, const char*, const char*);

#ifndef soap_read_ns__remove
#define soap_read_ns__remove(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__remove(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__remove * SOAP_FMAC2 soap_instantiate_ns__remove(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__remove * soap_new_ns__remove(struct soap *soap, int n = -1) { return soap_instantiate_ns__remove(soap, n, NULL, NULL, NULL); }

inline struct ns__remove * soap_new_req_ns__remove(struct soap *soap, std::vector<unsigned char >& interest) { struct ns__remove *_p = soap_instantiate_ns__remove(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__remove(soap, _p); _p->interest = interest; } return _p; }

inline struct ns__remove * soap_new_set_ns__remove(struct soap *soap, std::vector<unsigned char >& interest) { struct ns__remove *_p = soap_instantiate_ns__remove(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__remove(soap, _p); _p->interest = interest; } return _p; }

inline void soap_delete_ns__remove(struct soap *soap, struct ns__remove *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__remove(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__removeResponse
#define SOAP_TYPE_ns__removeResponse (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__removeResponse(struct soap*, struct ns__removeResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__removeResponse(struct soap*, const struct ns__removeResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__removeResponse(struct soap*, const char*, int, const struct ns__removeResponse *, const char*);
SOAP_FMAC3 struct ns__removeResponse * SOAP_FMAC4 soap_in_ns__removeResponse(struct soap*, const char*, struct ns__removeResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__removeResponse(struct soap*, const struct ns__removeResponse *, const char*, const char*);

#ifndef soap_write_ns__removeResponse
#define soap_write_ns__removeResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__removeResponse(soap, data),0) || soap_put_ns__removeResponse(soap, data, "ns:removeResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__removeResponse * SOAP_FMAC4 soap_get_ns__removeResponse(struct soap*, struct ns__removeResponse *, const char*, const char*);

#ifndef soap_read_ns__removeResponse
#define soap_read_ns__removeResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__removeResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__removeResponse * SOAP_FMAC2 soap_instantiate_ns__removeResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__removeResponse * soap_new_ns__removeResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns__removeResponse(soap, n, NULL, NULL, NULL); }

inline struct ns__removeResponse * soap_new_req_ns__removeResponse(struct soap *soap) { struct ns__removeResponse *_p = soap_instantiate_ns__removeResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__removeResponse(soap, _p); } return _p; }

inline struct ns__removeResponse * soap_new_set_ns__removeResponse(struct soap *soap, int *response) { struct ns__removeResponse *_p = soap_instantiate_ns__removeResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__removeResponse(soap, _p); _p->response = response; } return _p; }

inline void soap_delete_ns__removeResponse(struct soap *soap, struct ns__removeResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__removeResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__insert
#define SOAP_TYPE_ns__insert (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__insert(struct soap*, struct ns__insert *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__insert(struct soap*, const struct ns__insert *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__insert(struct soap*, const char*, int, const struct ns__insert *, const char*);
SOAP_FMAC3 struct ns__insert * SOAP_FMAC4 soap_in_ns__insert(struct soap*, const char*, struct ns__insert *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__insert(struct soap*, const struct ns__insert *, const char*, const char*);

#ifndef soap_write_ns__insert
#define soap_write_ns__insert(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__insert(soap, data),0) || soap_put_ns__insert(soap, data, "ns:insert", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__insert * SOAP_FMAC4 soap_get_ns__insert(struct soap*, struct ns__insert *, const char*, const char*);

#ifndef soap_read_ns__insert
#define soap_read_ns__insert(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__insert(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__insert * SOAP_FMAC2 soap_instantiate_ns__insert(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__insert * soap_new_ns__insert(struct soap *soap, int n = -1) { return soap_instantiate_ns__insert(soap, n, NULL, NULL, NULL); }

inline struct ns__insert * soap_new_req_ns__insert(struct soap *soap, std::vector<unsigned char >& data) { struct ns__insert *_p = soap_instantiate_ns__insert(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__insert(soap, _p); _p->data = data; } return _p; }

inline struct ns__insert * soap_new_set_ns__insert(struct soap *soap, std::vector<unsigned char >& data) { struct ns__insert *_p = soap_instantiate_ns__insert(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__insert(soap, _p); _p->data = data; } return _p; }

inline void soap_delete_ns__insert(struct soap *soap, struct ns__insert *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__insertResponse
#define SOAP_TYPE_ns__insertResponse (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__insertResponse(struct soap*, struct ns__insertResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__insertResponse(struct soap*, const struct ns__insertResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__insertResponse(struct soap*, const char*, int, const struct ns__insertResponse *, const char*);
SOAP_FMAC3 struct ns__insertResponse * SOAP_FMAC4 soap_in_ns__insertResponse(struct soap*, const char*, struct ns__insertResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__insertResponse(struct soap*, const struct ns__insertResponse *, const char*, const char*);

#ifndef soap_write_ns__insertResponse
#define soap_write_ns__insertResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__insertResponse(soap, data),0) || soap_put_ns__insertResponse(soap, data, "ns:insertResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__insertResponse * SOAP_FMAC4 soap_get_ns__insertResponse(struct soap*, struct ns__insertResponse *, const char*, const char*);

#ifndef soap_read_ns__insertResponse
#define soap_read_ns__insertResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__insertResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__insertResponse * SOAP_FMAC2 soap_instantiate_ns__insertResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__insertResponse * soap_new_ns__insertResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns__insertResponse(soap, n, NULL, NULL, NULL); }

inline struct ns__insertResponse * soap_new_req_ns__insertResponse(struct soap *soap) { struct ns__insertResponse *_p = soap_instantiate_ns__insertResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__insertResponse(soap, _p); } return _p; }

inline struct ns__insertResponse * soap_new_set_ns__insertResponse(struct soap *soap, int *response) { struct ns__insertResponse *_p = soap_instantiate_ns__insertResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__insertResponse(soap, _p); _p->response = response; } return _p; }

inline void soap_delete_ns__insertResponse(struct soap *soap, struct ns__insertResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__insertResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__read
#define SOAP_TYPE_ns__read (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__read(struct soap*, struct ns__read *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__read(struct soap*, const struct ns__read *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__read(struct soap*, const char*, int, const struct ns__read *, const char*);
SOAP_FMAC3 struct ns__read * SOAP_FMAC4 soap_in_ns__read(struct soap*, const char*, struct ns__read *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__read(struct soap*, const struct ns__read *, const char*, const char*);

#ifndef soap_write_ns__read
#define soap_write_ns__read(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__read(soap, data),0) || soap_put_ns__read(soap, data, "ns:read", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__read * SOAP_FMAC4 soap_get_ns__read(struct soap*, struct ns__read *, const char*, const char*);

#ifndef soap_read_ns__read
#define soap_read_ns__read(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__read(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__read * SOAP_FMAC2 soap_instantiate_ns__read(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__read * soap_new_ns__read(struct soap *soap, int n = -1) { return soap_instantiate_ns__read(soap, n, NULL, NULL, NULL); }

inline struct ns__read * soap_new_req_ns__read(struct soap *soap, std::vector<unsigned char >& interest) { struct ns__read *_p = soap_instantiate_ns__read(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__read(soap, _p); _p->interest = interest; } return _p; }

inline struct ns__read * soap_new_set_ns__read(struct soap *soap, std::vector<unsigned char >& interest) { struct ns__read *_p = soap_instantiate_ns__read(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__read(soap, _p); _p->interest = interest; } return _p; }

inline void soap_delete_ns__read(struct soap *soap, struct ns__read *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__read(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__readResponse
#define SOAP_TYPE_ns__readResponse (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__readResponse(struct soap*, struct ns__readResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__readResponse(struct soap*, const struct ns__readResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__readResponse(struct soap*, const char*, int, const struct ns__readResponse *, const char*);
SOAP_FMAC3 struct ns__readResponse * SOAP_FMAC4 soap_in_ns__readResponse(struct soap*, const char*, struct ns__readResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__readResponse(struct soap*, const struct ns__readResponse *, const char*, const char*);

#ifndef soap_write_ns__readResponse
#define soap_write_ns__readResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns__readResponse(soap, data),0) || soap_put_ns__readResponse(soap, data, "ns:readResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns__readResponse * SOAP_FMAC4 soap_get_ns__readResponse(struct soap*, struct ns__readResponse *, const char*, const char*);

#ifndef soap_read_ns__readResponse
#define soap_read_ns__readResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__readResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ns__readResponse * SOAP_FMAC2 soap_instantiate_ns__readResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__readResponse * soap_new_ns__readResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns__readResponse(soap, n, NULL, NULL, NULL); }

inline struct ns__readResponse * soap_new_req_ns__readResponse(struct soap *soap) { struct ns__readResponse *_p = soap_instantiate_ns__readResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__readResponse(soap, _p); } return _p; }

inline struct ns__readResponse * soap_new_set_ns__readResponse(struct soap *soap, std::vector<unsigned char >*response) { struct ns__readResponse *_p = soap_instantiate_ns__readResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns__readResponse(soap, _p); _p->response = response; } return _p; }

inline void soap_delete_ns__readResponse(struct soap *soap, struct ns__readResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__readResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data),0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data),0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data),0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);

#ifndef soap_write_PointerToint
#define soap_write_PointerToint(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToint(soap, data),0) || soap_put_PointerToint(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);

#ifndef soap_read_PointerToint
#define soap_read_PointerToint(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToint(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTostd__vectorTemplateOfunsignedByte
#define SOAP_TYPE_PointerTostd__vectorTemplateOfunsignedByte (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__vectorTemplateOfunsignedByte(struct soap*, std::vector<unsigned char >*const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__vectorTemplateOfunsignedByte(struct soap*, const char *, int, std::vector<unsigned char >*const*, const char *);
SOAP_FMAC3 std::vector<unsigned char >** SOAP_FMAC4 soap_in_PointerTostd__vectorTemplateOfunsignedByte(struct soap*, const char*, std::vector<unsigned char >**, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__vectorTemplateOfunsignedByte(struct soap*, std::vector<unsigned char >*const*, const char*, const char*);

#ifndef soap_write_PointerTostd__vectorTemplateOfunsignedByte
#define soap_write_PointerTostd__vectorTemplateOfunsignedByte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTostd__vectorTemplateOfunsignedByte(soap, data),0) || soap_put_PointerTostd__vectorTemplateOfunsignedByte(soap, data, "", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 std::vector<unsigned char >** SOAP_FMAC4 soap_get_PointerTostd__vectorTemplateOfunsignedByte(struct soap*, std::vector<unsigned char >**, const char*, const char*);

#ifndef soap_read_PointerTostd__vectorTemplateOfunsignedByte
#define soap_read_PointerTostd__vectorTemplateOfunsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostd__vectorTemplateOfunsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data),0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data),0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_std__vectorTemplateOfunsignedByte
#define SOAP_TYPE_std__vectorTemplateOfunsignedByte (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfunsignedByte(struct soap*, std::vector<unsigned char >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfunsignedByte(struct soap*, const std::vector<unsigned char >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfunsignedByte(struct soap*, const char*, int, const std::vector<unsigned char >*, const char*);
SOAP_FMAC3 std::vector<unsigned char >* SOAP_FMAC4 soap_in_std__vectorTemplateOfunsignedByte(struct soap*, const char*, std::vector<unsigned char >*, const char*);
SOAP_FMAC1 std::vector<unsigned char > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfunsignedByte(struct soap*, int, const char*, const char*, size_t*);

inline std::vector<unsigned char > * soap_new_std__vectorTemplateOfunsignedByte(struct soap *soap, int n = -1) { return soap_instantiate_std__vectorTemplateOfunsignedByte(soap, n, NULL, NULL, NULL); }

inline void soap_delete_std__vectorTemplateOfunsignedByte(struct soap *soap, std::vector<unsigned char >*p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfunsignedByte(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of soapH.h */
